

export const dummyItems = [
  {
    itemId: "ITM-001",
    itemName: "Mathematics Textbooks",
    location: "Room B12 - Shelf 3",
    dateAdded: "2025-01-10",
    status: "Excellent",
  },
  {
    itemId: "ITM-002",
    itemName: "Science Lab Coats",
    location: "Lab 2 - Cabinet 1",
    dateAdded: "2025-01-14",
    status: "Good",
  },
  {
    itemId: "ITM-003",
    itemName: "Projector HDMI Cables",
    location: "IT Storage - Drawer 4",
    dateAdded: "2025-02-02",
    status: "Excellent",
  },
  {
    itemId: "ITM-004",
    itemName: "Whiteboard Markers",
    location: "Staff Room - Cupboard",
    dateAdded: "2025-02-11",
    status: "Fair",
  },
  {
    itemId: "ITM-005",
    itemName: "Exam Pads",
    location: "Room F3 - Shelf 2",
    dateAdded: "2025-03-01",
    status: "Excellent",
  },
  {
    itemId: "ITM-006",
    itemName: "Art Brushes",
    location: "Art Room - Box A",
    dateAdded: "2025-03-05",
    status: "Good",
  },
  {
    itemId: "ITM-007",
    itemName: "Chemistry Beakers",
    location: "Lab 1 - Shelf 1",
    dateAdded: "2025-03-09",
    status: "Excellent",
  },
  {
    itemId: "ITM-008",
    itemName: "Sports Cones",
    location: "Gym Storage - Box 7",
    dateAdded: "2025-03-12",
    status: "Fair",
  },
  {
    itemId: "ITM-009",
    itemName: "Laptop Chargers",
    location: "IT Storage - Shelf 5",
    dateAdded: "2025-03-21",
    status: "Good",
  },
  {
    itemId: "ITM-010",
    itemName: "A4 Printing Paper",
    location: "Admin Office - Cabinet 3",
    dateAdded: "2025-03-25",
    status: "Excellent",
  },
  {
    itemId: "ITM-011",
    itemName: "Geometry Sets",
    location: "Room A2 - Drawer 2",
    dateAdded: "2025-03-28",
    status: "Damaged",
  },
  {
    itemId: "ITM-012",
    itemName: "Hand Sanitizers",
    location: "Hall Entrance - Shelf",
    dateAdded: "2025-03-30",
    status: "Good",
  },
  {
    itemId: "ITM-013",
    itemName: "English Literature Novels",
    location: "Library - Rack 4",
    dateAdded: "2025-04-01",
    status: "Damaged",
  },
  {
    itemId: "ITM-014",
    itemName: "Sports Bibs",
    location: "Gym Storage - Rack 1",
    dateAdded: "2025-04-03",
    status: "Fair",
  },
  {
    itemId: "ITM-015",
    itemName: "Clipboard Boards",
    location: "Admin Office - Drawer 1",
    dateAdded: "2025-04-05",
    status: "Damaged",
  },
  {
    itemId: "ITM-016",
    itemName: "Biology Specimen Jars",
    location: "Lab 3 - Shelf 2",
    dateAdded: "2025-04-06",
    status: "Good",
  },
  {
    itemId: "ITM-017",
    itemName: "Calculator Sets",
    location: "Room C1 - Cabinet",
    dateAdded: "2025-04-08",
    status: "Damaged",
  },
  {
    itemId: "ITM-018",
    itemName: "Paint Bottles",
    location: "Art Room - Shelf 5",
    dateAdded: "2025-04-11",
    status: "Fair",
  },
  {
    itemId: "ITM-019",
    itemName: "Rulers (30cm)",
    location: "Room D4 - Drawer 3",
    dateAdded: "2025-04-12",
    status: "Damaged",
  },
  {
    itemId: "ITM-020",
    itemName: "Spare Key Sets",
    location: "Security Office - Safe 2",
    dateAdded: "2025-04-14",
    status: "Bad",
  },
  {
    itemId: "ITM-021",
    itemName: "USB Flash Drives",
    location: "IT Storage - Drawer 1",
    dateAdded: "2025-04-17",
    status: "Damaged",
  },
  {
    itemId: "ITM-022",
    itemName: "Art Paper Rolls",
    location: "Art Room - Corner Rack",
    dateAdded: "2025-04-20",
    status: "Fair",
  },
  {
    itemId: "ITM-023",
    itemName: "Safety Goggles",
    location: "Lab 1 - Safety Cabinet",
    dateAdded: "2025-04-22",
    status: "Damaged",
  },
  {
    itemId: "ITM-024",
    itemName: "Stopwatches",
    location: "Sports Office - Drawer 2",
    dateAdded: "2025-04-25",
    status: "Bad",
  },
  {
    itemId: "ITM-025",
    itemName: "Printer Ink Cartridges",
    location: "Admin Office - Shelf 4",
    dateAdded: "2025-04-27",
    status: "Damaged",
  }
];
